# Generated by Django 4.1.7 on 2023-04-25 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profile_picture', models.FileField(upload_to='api_crud')),
                ('address', models.CharField(max_length=50)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to='api_crud.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
