# Generated by Django 4.1.7 on 2023-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0003_personprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='api_crud'),
        ),
    ]
