# Generated by Django 4.1.7 on 2023-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_classroom_personprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
